// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = " ",
                            CreatedDate = new DateTime(2024, 12, 15, 18, 48, 43, 569, DateTimeKind.Local).AddTicks(1071),
                            Details = "lorem",
                            ImageUrl = " ",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Rate = 200.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(2024, 12, 15, 18, 48, 43, 570, DateTimeKind.Local).AddTicks(8309)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = " ",
                            CreatedDate = new DateTime(2024, 12, 15, 18, 48, 43, 570, DateTimeKind.Local).AddTicks(8690),
                            Details = "lorem",
                            ImageUrl = " ",
                            Name = "Villa-Vip",
                            Occupancy = 6,
                            Rate = 500.0,
                            Sqft = 700,
                            UpdatedDate = new DateTime(2024, 12, 15, 18, 48, 43, 570, DateTimeKind.Local).AddTicks(8692)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = " ",
                            CreatedDate = new DateTime(2024, 12, 15, 18, 48, 43, 570, DateTimeKind.Local).AddTicks(8694),
                            Details = "lorem",
                            ImageUrl = " ",
                            Name = "Royal-Wild",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(2024, 12, 15, 18, 48, 43, 570, DateTimeKind.Local).AddTicks(8695)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
